"use client";
import { FormEvent, useState } from "react";
import type { Analysis, Evidence, Signal } from "@/lib/types";

const money=(n:number|null)=>n==null?"—":new Intl.NumberFormat("en-US",{notation:"compact",style:"currency",currency:"USD",maximumFractionDigits:1}).format(n);
const number=(n:number|null)=>n==null?"—":new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(n);
function EvidenceRow({e}:{e:Evidence}){return <a className="evidence" href={e.sourceUrl} target="_blank" rel="noreferrer"><span><b>{e.label}</b><small>SEC filing · {e.filedAt}</small></span><span>{e.unit==="number"?number(e.previous):money(e.previous)} → <b>{e.unit==="number"?number(e.current):money(e.current)}</b></span></a>}
function SignalCard({signal}:{signal:Signal}){return <article className={`signal ${signal.direction}`}><div className="signalTop"><span className="direction">{signal.direction}</span><span className="strength">Evidence {signal.strength}/100</span></div><h3>{signal.title}</h3><p className="summary">{signal.summary}</p><p>{signal.whyItMatters}</p><div className="evidenceList">{signal.evidence.map((e,i)=><EvidenceRow key={`${e.metric}-${i}`} e={e}/>)}</div><details><summary>Devil’s advocate</summary><p>{signal.counterpoint}</p></details></article>}
export default function Home(){const[ticker,setTicker]=useState("");const[data,setData]=useState<Analysis|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(false);async function analyze(symbol:string){setLoading(true);setError("");try{const r=await fetch(`/api/analyze?ticker=${encodeURIComponent(symbol)}`);const json=await r.json();if(!r.ok)throw new Error(json.error||"Analysis failed");setData(json)}catch(e){setError(e instanceof Error?e.message:"Analysis failed")}finally{setLoading(false)}}function submit(e:FormEvent){e.preventDefault();void analyze(ticker)}return <main><nav><div className="brand"><span>Kinkgo</span><span className="mark">X</span></div><span className="tag">Evidence before opinion.</span></nav><section className="hero"><p className="eyebrow">FUNDAMENTAL CHANGE INTELLIGENCE</p><h1>See the change.<br/><em>Before the market sees the story.</em></h1><p className="lead">KinkgoX turns SEC filings into an explainable chain from <b>Reality → Expectations → Price</b>. No black-box buy signal. Every claim links to evidence.</p><form onSubmit={submit}><input aria-label="Ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="Enter US ticker — e.g. MSFT" maxLength={10}/><button disabled={loading||!ticker.trim()}>{loading?"Reading filings…":"Analyze change"}</button></form><button className="demo" onClick={()=>void analyze("DEMO")} disabled={loading}>or open the instant demo</button>{error&&<p className="error" role="alert">{error}</p>}</section>{data&&<section className="dashboard" aria-live="polite"><header className="company"><div><p className="eyebrow">KINKGOX COMPANY DNA</p><h2>{data.company} <span>{data.ticker}</span></h2><p>CIK {data.cik} · {data.mode==="live"?"Live SEC data":"Illustrative demo data"}</p></div><div className={`regime ${data.regime}`}><small>KinkgoX Pulse</small><b>{data.regime}</b><span>{data.confidence}% thesis confidence</span></div></header><div className="thesisGrid"><article><p className="eyebrow">THESIS ENGINE</p><h3>Current evidence map</h3><p>{data.thesis}</p></article><article className="devil"><p className="eyebrow">DEVIL’S ADVOCATE</p><h3>How this could be wrong</h3><p>{data.devilAdvocate}</p></article></div><div className="sectionTitle"><div><p className="eyebrow">HIDDEN SIGNALS</p><h2>Changes behind the headline</h2></div><span>{data.signals.length} checks</span></div><div className="signals">{data.signals.map(s=><SignalCard key={s.id} signal={s}/>)}</div><article className="ledger"><p className="eyebrow">EVIDENCE LEDGER</p><h2>Audit the thesis</h2><p>Every metric above retains its filing date and source link. The model exposes its counterarguments instead of hiding uncertainty.</p>{data.warnings.map(w=><p className="warning" key={w}>⚠ {w}</p>)}</article></section>}<footer>KinkgoX Alpha · Fundamental Change Intelligence · Educational research only</footer></main>}
