import { z } from "zod";
import type { FundamentalPeriod } from "./engine";

const CompanyTickersSchema=z.record(z.object({cik_str:z.number(),ticker:z.string(),title:z.string()}));
type FactUnit={fy?:number;fp?:string;form?:string;filed?:string;val:number;accn?:string};
type CompanyFacts={facts?:{"us-gaap"?:Record<string,{units?:Record<string,FactUnit[]>}>}};
const TAGS={revenue:["RevenueFromContractWithCustomerExcludingAssessedTax","Revenues","SalesRevenueNet"],grossProfit:["GrossProfit"],operatingIncome:["OperatingIncomeLoss"],operatingCashFlow:["NetCashProvidedByUsedInOperatingActivities"],capex:["PaymentsToAcquirePropertyPlantAndEquipment"],inventory:["InventoryNet"],receivables:["AccountsReceivableNetCurrent","AccountsNotesAndLoansReceivableNetCurrent"],debt:["LongTermDebtAndFinanceLeaseObligationsCurrent","LongTermDebtCurrent","LongTermDebtNoncurrent"],shares:["WeightedAverageNumberOfDilutedSharesOutstanding"]} as const;
const headers={"User-Agent":process.env.SEC_USER_AGENT||"KinkgoX/0.1 engineering@kingkox.local","Accept-Encoding":"gzip, deflate","Accept":"application/json"};
async function secJson<T>(url:string):Promise<T>{const res=await fetch(url,{headers,next:{revalidate:21600}});if(!res.ok)throw new Error(`SEC request failed (${res.status})`);return res.json() as Promise<T>}
function annualSeries(facts:CompanyFacts,tags:readonly string[]):FactUnit[]{for(const tag of tags){const units=facts.facts?.["us-gaap"]?.[tag]?.units;if(!units)continue;const values=units.USD||units.shares||Object.values(units)[0];if(values?.length)return values.filter(x=>x.form==="10-K"&&x.fy&&x.fp==="FY").sort((a,b)=>(b.fy??0)-(a.fy??0));}return[]}
function valueFor(series:FactUnit[],fy:number){const matches=series.filter(x=>x.fy===fy);return matches.length?matches[matches.length-1].val:null}
export async function fetchAnalysisInput(ticker:string){const clean=ticker.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(clean))throw new Error("Enter a valid US ticker symbol.");const map=CompanyTickersSchema.parse(await secJson<unknown>("https://www.sec.gov/files/company_tickers.json"));const company=Object.values(map).find(x=>x.ticker.toUpperCase()===clean);if(!company)throw new Error("Ticker not found in the SEC company list.");const cik=String(company.cik_str).padStart(10,"0");const facts=await secJson<CompanyFacts>(`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`);const series=Object.fromEntries(Object.entries(TAGS).map(([k,t])=>[k,annualSeries(facts,t)])) as Record<keyof typeof TAGS,FactUnit[]>;const years=[...new Set(series.revenue.map(x=>x.fy).filter((x):x is number=>!!x))].sort((a,b)=>b-a).slice(0,3);if(years.length<2)throw new Error("Not enough comparable annual SEC data was found.");const periods:FundamentalPeriod[]=years.map(fy=>{const anchor=series.revenue.find(x=>x.fy===fy);const accn=anchor?.accn?.replaceAll("-","")||"";return{filedAt:anchor?.filed||String(fy),sourceUrl:accn?`https://www.sec.gov/Archives/edgar/data/${company.cik_str}/${accn}/`:"https://www.sec.gov/edgar/search/",revenue:valueFor(series.revenue,fy),grossProfit:valueFor(series.grossProfit,fy),operatingIncome:valueFor(series.operatingIncome,fy),operatingCashFlow:valueFor(series.operatingCashFlow,fy),capex:valueFor(series.capex,fy),inventory:valueFor(series.inventory,fy),receivables:valueFor(series.receivables,fy),debt:valueFor(series.debt,fy),shares:valueFor(series.shares,fy)}});return{ticker:clean,company:company.title,cik,periods}}
